apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: istio-gateway-cert
  namespace: istio-ingress
spec:
  secretName: gateway-secret-tls
  commonName: {{ .Values.domainName }}
  dnsNames:
    - {{ .Values.domainName }}
    - "*.{{ .Values.domainName }}"
  duration: 2160h0m0s # 90d
  renewBefore: 360h0m0s # 15d
  subject:
    organizations:
      - COVAXIN
  usages:
    - server auth
  issuerRef:
    name: letsencrypt
    kind: ClusterIssuer
    group: cert-manager.io
