installCRDs: true

# the securityContext is required, so the pod can access files required to assume the IAM role
securityContext:
  fsGroup: 1001

extraArgs: [--dns01-recursive-nameservers-only,--dns01-recursive-nameservers=205.251.193.56:53]