apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
  name: argocd-vsvc
spec:
  gateways:
    - istio-ingress/gateway
  hosts:
    - "argocd.${domain}"
  http:
    - name: argocd-server-service
      match:
        - uri:
            prefix: /
      route:
        - destination:
            host: argo-cd-argocd-server
            port:
              number: 80
