apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: github-repo-token
  namespace: argocd
  labels:
    argocd.argoproj.io/secret-type: repository
spec:
  refreshInterval: 30m
  secretStoreRef:
    name: aws-backend
    kind: ClusterSecretStore
  target:
    name: github-repo-token
    creationPolicy: Owner
    template:
      metadata:
        labels:
          argocd.argoproj.io/secret-type: repository
      engineVersion: v2
      data:
        type: "git"
        url: ${github_repo_url}
        username: "not-used"
        password: "{{ .token }}"
  data:
    - secretKey: token
      remoteRef:
        conversionStrategy: Default
        decodingStrategy: None
        key: GITHUB_REPO_TOKEN
